# Generated by Django 5.1.3 on 2025-01-07 16:37

import django.db.models.deletion
import staff_panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike_portfolio', '0004_remove_bicycle_repair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('issue_description', models.TextField(max_length=1000)),
                ('issue_image', models.ImageField(default='default.png', upload_to=staff_panel.models.custom_upload_to)),
                ('is_fixed', models.BooleanField(default=False)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('date_fixed', models.DateField(blank=True, null=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_logs', to='bike_portfolio.bicycle')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_issues', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
