# Generated by Django 5.1.3 on 2025-01-12 16:28

import staff_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=staff_panel.models.custom_upload_to),
        ),
    ]
