# Generated by Django 5.1.3 on 2024-11-19 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=30)),
                ('generation', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(max_length=200)),
                ('year_production', models.IntegerField()),
                ('color_primary', models.CharField(max_length=30)),
                ('color_secondary', models.CharField(blank=True, max_length=30, null=True)),
                ('frame_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('S/M', 'S/M'), ('M', 'M'), ('M/L', 'M/L'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('frame_material', models.CharField(choices=[('carbon', 'Carbon'), ('steel', 'Steel'), ('aluminium', 'Aluminium'), ('titanium', 'Titanium')], max_length=30)),
                ('wheel_size', models.FloatField(choices=[('24', 24), ('26', 26), ('27.5', 27.5), ('29', 29)])),
                ('tire_size_width', models.FloatField()),
                ('type', models.CharField(max_length=30)),
                ('suspension_front', models.BooleanField(default=True)),
                ('suspension_back', models.BooleanField(default=True)),
                ('weight', models.FloatField()),
                ('prize_buy', models.FloatField()),
                ('prize_rent', models.FloatField()),
            ],
        ),
    ]
