# Generated by Django 5.1.3 on 2025-01-03 10:18

import bike_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image_main',
            field=models.ImageField(default='default.png', upload_to=bike_portfolio.models.custom_upload_to),
        ),
    ]
