# Generated by Django 5.1.3 on 2024-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='type',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='is_serviceable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='frame_material',
            field=models.CharField(choices=[('carbon', 'Carbon'), ('steel', 'Steel'), ('aluminium', 'Aluminium'), ('titanium', 'Titanium')], max_length=9),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='wheel_size',
            field=models.FloatField(choices=[(24.0, '24'), (26.0, '26'), (27.5, '27.5'), (29.0, '29')]),
        ),
    ]
