# Generated by Django 5.1.3 on 2024-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0003_alter_bicycle_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='image_main',
            field=models.ImageField(default='default.jpg', upload_to='main_bike_image'),
        ),
    ]
