# Generated by Django 5.1.3 on 2024-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0004_bicycle_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image_main',
            field=models.ImageField(default='default.png', upload_to='main_bike_image'),
        ),
    ]
