# Generated by Django 5.1.3 on 2025-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0004_remove_bicycle_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='wheel_size',
            field=models.CharField(choices=[('24.0"', '24'), ('26.0"', '26'), ('27.5"', '27.5'), ('29.0"', '29')], max_length=10),
        ),
    ]
