# Generated by Django 5.1.3 on 2025-02-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0005_alter_bicycle_wheel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='wheel_size',
            field=models.CharField(choices=[('24"', '24'), ('26"', '26'), ('27.5"', '27.5'), ('29"', '29')], max_length=10),
        ),
    ]
