# Generated by Django 5.1.3 on 2024-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0006_alter_bicycle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
