# Generated by Django 5.1.3 on 2025-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_portfolio', '0006_alter_bicycle_wheel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'ordering': ['-is_available']},
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='wheel_size',
            field=models.CharField(choices=[('24"', '24"'), ('26"', '26"'), ('27.5"', '27.5"'), ('29"', '29"')], max_length=10),
        ),
    ]
